update_component_config:
  target:
    entity:
      integration: openems
      domain:
        - number
  fields:
    value:
      required: true
      selector:
        text:

update_value:
  target:
    entity:
      integration: openems
      domain:
        - sensor
        - binary_sensor
      supported_features:
        - openems.OpenEMSEntityFeature.WRITE
  fields:
    value:
      required: true
      selector:
        text:
